#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RUN_ID="${CODEBASE_RUN_ID:-swecl-smoke-qwen35-9b-r1-tp2-$(date +%Y%m%d-%H%M%S)}"

export CODEBASE_RUN_ID="${RUN_ID}"
export CODEBASE_NGPU="${CODEBASE_NGPU:-2}"
export CODEBASE_TP="${CODEBASE_TP:-2}"
export CODEBASE_CP="${CODEBASE_CP:-1}"
export CODEBASE_NUM_ROLLOUT="${CODEBASE_NUM_ROLLOUT:-1}"
export CODEBASE_ROLLOUT_BATCH_SIZE="${CODEBASE_ROLLOUT_BATCH_SIZE:-1}"
export CODEBASE_N_SAMPLES="${CODEBASE_N_SAMPLES:-2}"
export CODEBASE_GLOBAL_BATCH_SIZE="${CODEBASE_GLOBAL_BATCH_SIZE:-2}"
export CODEBASE_DYNAMIC_GLOBAL_BATCH="${CODEBASE_DYNAMIC_GLOBAL_BATCH:-1}"
export CODEBASE_NUM_ACTS_CAP="${CODEBASE_NUM_ACTS_CAP:-2}"
export CODEBASE_MAX_STEPS_PER_ISSUE="${CODEBASE_MAX_STEPS_PER_ISSUE:-3}"
export CODEBASE_MAX_RESP="${CODEBASE_MAX_RESP:-1200}"
export CODEBASE_EVAL_INTERVAL="${CODEBASE_EVAL_INTERVAL:-0}"
export CODEBASE_SAVE_INTERVAL="${CODEBASE_SAVE_INTERVAL:-0}"
export CODEBASE_SEQ_LEN="${CODEBASE_SEQ_LEN:-32768}"
export CODEBASE_MAX_TOK_PER_GPU="${CODEBASE_MAX_TOK_PER_GPU:-20480}"
export CODEBASE_SGLANG_MEM="${CODEBASE_SGLANG_MEM:-0.5}"
export CODEBASE_USE_WANDB="${CODEBASE_USE_WANDB:-1}"
export CODEBASE_WANDB_RUN_ID="${CODEBASE_WANDB_RUN_ID:-${RUN_ID}}"
export WANDB_PROJECT="${WANDB_PROJECT:-miles-codebase-adaption}"
export WANDB_GROUP="${WANDB_GROUP:-swecl-smoke-qwen3.5-9B}"
export CODEBASE_PROMPT_DATA="${CODEBASE_PROMPT_DATA:-${SCRIPT_DIR}/data/swecl_train_episodes.jsonl}"
export CODEBASE_BASELINE_ARTIFACT="${CODEBASE_BASELINE_ARTIFACT:-${SCRIPT_DIR}/data/baseline_merged.json}"
unset CODEBASE_RAY_NO_WAIT

exec "${SCRIPT_DIR}/launch_codebase_adaption_apptainer.sh"
