# Qwen2.5-1.5B
model:
  swiglu: true
  num_layers: 28
  hidden_size: 1536
  ffn_hidden_size: 8960
  num_attention_heads: 12
  use_rotary_position_embeddings: true
  disable_bias_linear: true
  add_qkv_bias: true
  normalization: RMSNorm
  norm_epsilon: 1e-6
  rotary_base: 10000
  group_query_attention: true
  num_query_groups: 2
  vocab_size: 151936
