# Qwen3-32B
model:
  swiglu: true
  num_layers: 64
  hidden_size: 5120
  ffn_hidden_size: 25600
  num_attention_heads: 64
  group_query_attention: true
  num_query_groups: 8
  use_rotary_position_embeddings: true
  disable_bias_linear: true
  normalization: RMSNorm
  norm_epsilon: 1e-6
  rotary_base: 1000000
  vocab_size: 151936
  kv_channels: 128
  qk_layernorm: true
  untie_embeddings_and_output_weights: true
