# Qwen2.5-3B
model:
  swiglu: true
  num_layers: 36
  hidden_size: 2048
  ffn_hidden_size: 11008
  num_attention_heads: 16
  use_rotary_position_embeddings: true
  disable_bias_linear: true
  add_qkv_bias: true
  normalization: RMSNorm
  norm_epsilon: 1e-6
  rotary_base: 1000000
  group_query_attention: true
  num_query_groups: 2
  vocab_size: 151936
