# Qwen3-30B-A3B (MoE)
model:
  disable_bias_linear: true
  qk_layernorm: true
  group_query_attention: true
  num_attention_heads: 32
  num_query_groups: 4
  kv_channels: 128
  num_layers: 48
  hidden_size: 2048
  ffn_hidden_size: 6144
  normalization: RMSNorm
  position_embedding_type: rope
  norm_epsilon: 1e-6
  rotary_percent: 1.0
  swiglu: true
  untie_embeddings_and_output_weights: true
  vocab_size: 151936
  rotary_base: 1000000
  use_rotary_position_embeddings: true
  # MoE
  moe_ffn_hidden_size: 768
  moe_router_score_function: softmax
  moe_token_dispatcher_type: alltoall
  moe_router_topk: 8
  moe_layer_freq: "[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
  num_experts: 128
  moe_grouped_gemm: true
  moe_token_drop_policy: probs
  moe_router_dtype: fp32
  moe_permute_fusion: true
  moe_aux_loss_coeff: 0
