# Qwen3-Next-80B-A3B (MoE)
model:
  spec: '"miles_plugins.models.qwen3_next" "get_qwen3_next_spec"'
  disable_bias_linear: true
  qk_layernorm: true
  group_query_attention: true
  num_attention_heads: 16
  num_query_groups: 2
  kv_channels: 256
  num_layers: 48
  hidden_size: 2048
  ffn_hidden_size: 5120
  use_gated_attention: true
  normalization: RMSNorm
  apply_layernorm_1p: true
  position_embedding_type: rope
  norm_epsilon: 1e-6
  rotary_percent: 0.25
  swiglu: true
  untie_embeddings_and_output_weights: true
  vocab_size: 151936
  rotary_base: 10000000
  # MoE
  moe_ffn_hidden_size: 512
  moe_shared_expert_intermediate_size: 512
  moe_router_score_function: softmax
  moe_token_dispatcher_type: alltoall
  moe_router_topk: 10
  moe_layer_freq: "[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
  num_experts: 512
  moe_grouped_gemm: true
  moe_token_drop_policy: probs
  moe_router_dtype: fp32
  moe_permute_fusion: true
  moe_aux_loss_coeff: 0
  # Qwen3-Next specific
  attention_output_gate: true
  moe_shared_expert_gate: true
